services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: github-secrets-backend-dev
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
    volumes:
      - ./backend/data:/app/data
      - ./backend/src:/app/src
    networks:
      - app-network
    restart: unless-stopped
    command: npm run dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: github-secrets-frontend-dev
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  backend-data: